### PR TITLE
Created/Updated Table of Contents

### PR DESCRIPTION
**Pull request by nevarez-emil**
I made the TOC more readable, and organize. I also added/fixed links to relevant topics.

### CODE REVIEW

**Comment by mikeizbicki** [comment]
There are too many commits here.  I can't tell what you actually changed.  You need to squash all of these commits into a single commit before I can look at this.

**Comment by nevarez-emil** [comment]
How would I go about compressing these into a less jumbled mess? Lots of the commits are from me testing changes in .md formatting which I don't know how to test unless I push it to github.

**Comment by mikeizbicki** [comment]
See the tutorial at: https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/textbook/tools/git/managingForkedRepo

**Comment by nevarez-emil** [comment]
Got it. I'm going to finish up this last edit and then compress my commits, then I'll submit another pull request.

**Pull request closed without merging**
