### PR TITLE
HW4 Final Submission

### PR DESCRIPTION
**Pull request by kevdev158**
Finished script and tutorial.
We really enjoyed CS100, thank you for teaching us! Have a great summer!

@dtran049 @jtran071

### CODE REVIEW

**Comment by mikeizbicki** [comment]
This is almost an amazing writeup, but it falls short.  There are a number of technical errors, and the overall writeup lacks polish.  For example, your actual recipe files look a bit ugly because they don't use markdown syntax.  If I were learning how to webscrape for the first time, this is exactly the sort of example I would want, but I wouldn't be able to follow your explanations.  So I'm giving you 85/100.

As-is, I suspect very few people on the internet will want to read this.  But it would only take a few hours more work to make it so that thousands of people would want to read it.  Please let me know if you're interested in doing any more work on it like this.

**Comment by kevdev158** [comment]
We'd be interested in continuing on working on the write up.

**Comment by mikeizbicki** [comment]
If you come to my office hours tomorrow, we can discuss in more detail how to improve it.

**Comment by kevdev158** [comment]
None of us are in Riverside anymore.

**Comment by mikeizbicki** [comment]
Okay.  I'm not sure how I can help you improve it then.

**Comment by kevdev158** [comment]
Is it possible to go over it online?

**Pull request merged**
