### PR TITLE
added student Vincent Chang

### PR DESCRIPTION
**Pull request by vinkert**
enrolling in cs100

### CODE REVIEW

**Comment by busrac** [comment]
The first two lines in the file are duplicated. Can you fix that and merge the commits into a single one? The tutorial for merging is here:
https://github.com/mikeizbicki/ucr-cs100/tree/2015spring/textbook/tools/git/managaing-your-forked-repo

**Comment by vinkert** [comment]
When I try to push the corrected version I am given the error:
fatal: HTTP request failed (shown in this image
http://i.imgur.com/hrEgeMj.png)
Is there something I am doing wrong?

On Mon, Apr 6, 2015 at 9:02 PM, E. Busra Celikkaya <notifications@github.com

**Comment by busrac** [comment]
It seems like you forgot to run the "cs100" script after ssh'ing to hammer.

**Comment by vinkert** [comment]
Ok I fixed it

**Comment by mikeizbicki** [comment]
I have manually added your file, so there is no need for any further action.

**Pull request closed without merging**
