### PR TITLE
I just update README.md

### PR DESCRIPTION
**Pull request by mxu008**
When we update the forked repository on the github servers, I think we should run the command "git push origin cs100-2014fall" instead of "git push origin master". We should always check what branch we are in.

### CODE REVIEW

**Comment by tkimva** [comment]
Thanks! remind Prof. Izbicki to assign you extra credit for this.

**Comment by mxu008** [comment]
@mikeizbicki  I just updated README.md and sorry for the trouble.

**Comment by mikeizbicki** [comment]
Good job.  Right now, you have two commits, which is fine.  In the future, try to make only a single commit for changes like this.

**Comment by mikeizbicki** [comment]
+5 pts extra credit

**Pull request merged**
