### PR TITLE
Output Formatting in C++ - Squashed Commits

### PR DESCRIPTION
**Pull request by npsark**
Ok, I'm pretty sure I correctly squashed my latest commits. Let me know if this is what you are looking for.

### CODE REVIEW

**Comment by mikeizbicki** [comment]
No, it's still showing up as lots of different commits.

**Comment by npsark** [comment]
I'm a bit confused. I'm following the steps in the link you gave me but it just doesn't seem to be working. I cloned the ucr-cs100 repo from my account onto my computer. I removed all of my hw4 files from the repo. I created a new branch called hw4 and added the hw4 files to that branch. I checked out back to the first branch(cs100-2014fall) and ran git merge on the new branch. I ran git reset origin/cs100-2014fall. Then I ran git add --all and git commit. Finally, I pushed the repo back to my account on github.com. But when I make a pull request, it still shows all of the commits from before. Any idea where I'm going wrong?

**Comment by mikeizbicki** [comment]
I think it will be easier to fix this in person.  Can you come by office
hours tomorrow?

**Comment by npsark** [comment]
I actually have lecture tomorrow from 3:40-5:10, so unfortunately no. Are you on campus anytime between 11:00-12:30 or 2:00-3:30?

**Comment by mikeizbicki** [comment]
I'm not available then, sorry.  Maybe you can try another set of instructions. Other people have had success following this set of instructions: http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository

**Pull request closed without merging**
