### PR TITLE
fixed bugs

### PR DESCRIPTION
**Pull request by tristanzickovich**

### CODE REVIEW

**Comment by mikeizbicki** [comment]
Great work! +20 pts extra credit.

**Comment by mikeizbicki** [comment]
You haven't yet given me or the TAs contributor access to your github repo yet, so I can't give you the points.

**Comment by tristanzickovich** [comment]
Oh yeah, Ill do that now.  I had to delete my fork of this repo.

All done

**Comment by tristanzickovich** [comment]
Is 20 points the cap on ec from typo fixes?

**Pull request merged**
