### PR TITLE
First draft of HW4, Boost Tokenizer tutorialk

### PR DESCRIPTION
**Pull request by glaceeeee**
Wrote escaped list and offset tutorials and added to the README file

To do:
- Add examples to escaped list and offset tutorials
- Edit the README for better flow
- Add parts on the constructors for the escaped list and offset tutorials
- Cut down on some wordiness/ get to the point faster (mainly for the escaped list tutorial)

### CODE REVIEW

**Comment by glaceeeee** [comment]
Also, I think I'm going to take out the quote in the beginning of the README.

**Comment by mikeizbicki** [comment]
The final product should just be a single file, not one for each class.

**Comment by mikeizbicki** [comment]
The main thing you need to focus on is incorporating your material more seamlessly into the existing tutorial.  It shouldn't feel like something that was tacked on afterward.

Any questions?

**Comment by glaceeeee** [comment]
Thanks for the feedback!

Are you going to be available to read later drafts? If so, would I just need to do another pull request for that draft?

**Comment by mikeizbicki** [comment]
Yes, just issue another pull request.

**Pull request closed without merging**
