### PR TITLE
My corrections

### PR DESCRIPTION
**Pull request by Anthony1234567**
These include broken links, typos, grammar, and sentence editing made to the textbook

### CODE REVIEW

**Comment by mikeizbicki** [comment]
You have so many commits here, it's impossible for me to actually look through them and tell what you've changed.  You'll need to squash them all into a single commit before I can accept your changes.  There's a tutorial in the textbook/tools/git folder on how to do this.

**Comment by Anthony1234567** [comment]
What if the changes are made by other students by the time I get to them?

**Comment by mikeizbicki** [comment]
Then they will get the credit.

**Comment by mikeizbicki** [comment]
Then they will get credit for the corrections.  You get credit not for identifying a problem, but for providing a fix.  At this point, you haven't fixed anything.

**Comment by Anthony1234567** [comment]
But I did provide a fix. The amount of time it would take to check my changes which total to about 105 corrections and 78 deletions would take you only a couple of minutes. What if the changes were made individually? I really only fixed obvious spelling errors and a pair of broken links. There was no specification given on the format in which the pull request was to be submitted initially.

**Comment by mikeizbicki** [comment]
Part of contributing to open source projects is making pull requests that are easy for the owner to accept.  And part of this means making all related changes into a single commit.  This is a skill that you absolutely must learn.

I won't be accepting #817, so you can still get the extra credit for this.

**Pull request closed without merging**
