### PR TITLE
hw4 submission - GitMap

### PR DESCRIPTION
**Pull request by mchen046**
I apologize in advance, there are some rogue commits that appeared earlier in the quarter. What is the best course of action to remove the commit messages in this case?

Again, this is for I, @mchen046, @ttruo018, and @ykamo001.

### CODE REVIEW

**Comment by mchen046** [comment]
Here's a link to the git repo: https://github.com/ykamo001/GitMap

**Comment by mikeizbicki** [comment]
We should talk about this in person.  Can you all make my office hours tomorrow?

**Comment by ykamo001** [comment]
I live in the By Area, so I won't be in Riverside until June 22 for summer session, sorry. Won't be able to come in for office hours.

**Comment by mchen046** [comment]
I'm currently living 50 miles away from riverside, but if it's absolutely necessary I'll make the drive over there tomorrow. 

@ttruo018 says he'll be able to make it to your office hours tomorrow.

**Comment by mikeizbicki** [comment]
You did not do what you proposed in #1519.  In particular, you said you would create a map of the repo using latex, and the output would be an image.  This would be very useful.  For example, I could automate the creation of all the repo images used in the textbook folder.

But if I understand your writeup, then all you're doing is printing the information from `git log` but visualized on the terminal in a slightly different way.  I don't see what the contribution is because I can get the exact same effect with a one line git command.  The `--pretty` parameter lets me specify in detail how I want each commit to be displayed, and I could use this parameter instead of your bash script to format the output the way you have.

Is the above correct?

**Comment by mchen046** [comment]
Correct. We abandoned our original idea of using LaTeX. While we were writing the shell script, we extracted information using `git branch` and `git log`. From there, we decided to create dynamic box shapes using a mix of ascii characters and labeled the most recent commit of each branch. At the time, we were not aware of the `--pretty` parameter.

If you would like us to generate the .tex file that can then be converted into a pdf, we will write it as soon as possible.

**Comment by mikeizbicki** [comment]
As-is, I'm struggling to find ways to give you any points.  If you can come up with a _specific_ plan on how you will fix the project and how long it will take, I'll _consider_ entering grade delays for you and upgrading your grade when you complete the project.  The final project would have to be _amazing_ and will suffer a significant penalty for being late.

**Pull request closed without merging**
