### PR TITLE
merging mike's branch into mine

### PR DESCRIPTION
**Pull request by ChemicalWonders**
i think i'm not sure what i'm doing.

### CODE REVIEW

**Comment by hgarc014** [comment]
if you haven't already made the changes, then I usually like to follow this pattern:

fetch mike's upstream
merge his upstream/masterbranch
and update my forked repository so that I am up to date, then I would make the necessary changes, update my forked repository and issue a pull request.

**Comment by ChemicalWonders** [comment]
the problem is that when I try to fetch mike's upstream, nothing happens.

**Comment by hgarc014** [comment]
then you probably haven't set up your upstream.
This line will setup your upstream:
`git remote add upstream https://github.com/mikeizbicki/ucr-cs100.git`

**Comment by ChemicalWonders** [comment]
No. I did. Just check it out when we have our planning meeting. :)

**Comment by ChemicalWonders** [comment]
nevermind i fixed it! :D

**Pull request closed without merging**
