### PR TITLE
Updated syscalls

### PR DESCRIPTION
**Pull request by skama004**
We updated the syscalls more on what you said. We made it more example based and followed the criteria a lot more closely. We also removed the extra files that were there and now we only have the files we added.

### CODE REVIEW

**Comment by skama004** [comment]
Please let us know if we did enough to get more points. My partners are @divyanshch and @hannesphillips. If we have to come in tomorrow, a lot of us have already gone home, and I live kind of far, but if needed I can make the drive down to talk to you more if needed.

**Comment by mikeizbicki** [comment]
You're still not following the styleguide.

**Comment by skama004** [comment]
Will we still only be getting 50 points with all the changes? Is there anything we can do to still change this so it can actually get merged and we can get our points up or is it too late?

**Comment by skama004** [comment]
I realized it will be tough for me to come out to office hours tomorrow morning because I live really far from Riverside and won't have proper transportation tomorrow. Is there any way we can work on it a little bit more with some added time?

**Comment by ghost** [comment]
Why was this issue reopened?

**Comment by mikeizbicki** [comment]
@aso001 Just due so I could merge it.

**Pull request merged**
