### PR TITLE
Edit formatting and wording to match overall structure

### PR DESCRIPTION
**Pull request by ghost**
I was originally had trouble committing to the wrong repository

### CODE REVIEW

**Comment by mikeizbicki** [comment]
Your two commits look the same to me.  Why are there two?

**Comment by ghost** [comment]
The two changes I made from the original format was clarify one of the titles from "it" to  Regex and the list at the bottom to the following format with bullet points. The extra plus mark is a bullet point. I have included screenshots to point out what I have changed. Also the reason why there are two commits because I was merging commits to a different branch before I made the pull request.
Original:
o1
o2

Changes:
c1
c2

**Comment by mikeizbicki** [comment]
But why are there two commits?

**Comment by aso001** [comment]
Re-posted with correct commits.

**Comment by ghost** [comment]
There are two commits because I accidentally edited the content from one of my branches aso001-patch-1 and tried to merge it with my local copy ucr-cs100 branch 2015spring to fix it.  I only intended to push  commit '3ef249c'  but I could not find commit '19ac03c' to squash it.

**Comment by mikeizbicki** [comment]
I can't merge until the commits are squashed.

**Pull request closed without merging**
