### PR TITLE
added vim-videos tutorial

### PR DESCRIPTION
**Pull request by 2c2c**
Removed assumptions section

### CODE REVIEW

**Comment by mikeizbicki** [comment]
I think you can make the intro a bit better too still.

**Comment by 2c2c** [comment]
I'm actually unsure what I should do/not do in it

**Comment by mikeizbicki** [comment]
These sentences:

```
It's not straightforward identifying whether someone is a beginner, expert,
or any other classification in skill. In general it's just going to
correlate to how quick you can use stuff available to you to edit text.
```

don't add anything, so take them out.

Then just say something about how knowing these other commands will make
you more productive.

**Comment by 2c2c** [comment]
File's been changed. Nailed it.

**Comment by mikeizbicki** [comment]
good job!

**Pull request merged**
