### PR TITLE
Made some of the requested changes. Looking for feedback.

### PR DESCRIPTION
**Pull request by thekevinlemon2**
I implemented the changes you asked for on part of the README. I was looking for feedback before I went ahead with the rest of the writeup. Also, I can't seem to get the pictures centered. I'm using the ![alt text] followed by the image url and appending <center> in front and </center> behind does not seem to work.

### CODE REVIEW

**Comment by thekevinlemon2** [comment]
I also added a diagram summarizing the whole class enrollment process!

**Comment by mikeizbicki** [comment]
Those new diagrams look REALLY nice!  Excellent!

I like the summary diagram too at the end!  Good idea!

**Comment by thekevinlemon2** [comment]
Hey Mike I'm done adding all the pictures. Unfortuately I still can't seem to get the pictures to be centered even though I followed your format. Also looking for more feedback!

**Comment by thekevinlemon2** [comment]
Hey Mike I'm just making a follow up post because you haven't responded yet. The pictures should be showing up fine now. Still looking for a final revision/feedback.

**Comment by mikeizbicki** [comment]
All of those diagrams look really nice.  Good job!

The images still need to be added to the github repo though.  That way, someone can clone the repo and have access to all the materials even if they don't have access to the internet to view the files on imgur.

Finally, for the screnshot images.  Make them have only a single circle per image.  It'll be a lot more pictures, but I think it'll be a bit clearer that way.

**Comment by thekevinlemon2** [comment]
Got the pictures into the repository and linked them. I also separated it to one screenshot per button and added borders between the pictures. Looking for feedback!

**Comment by mikeizbicki** [comment]
Looks good.  I've merged all the changes.  Thanks!

**Pull request closed without merging**
