### PR TITLE
HW4 - GDB Tutorial

### PR DESCRIPTION
**Pull request by ManjunathChet**
Here is the final version of my HW4 submission.
- Ex1: I changed the README so the code is seperated into different blocks. Each instruction is followed by a block of code that shows how that command is run.
- Ex2: The `info` function is now stripped of the syscalls that are used in hw2. The output is much shorter and easier to follow.
- Ex3: As you requested, example 3 is the GDB lab. I changed the introduction so it fits with the rest of the tutorial. Other than that, it is the same file.

Also, I went to the writing center to have my README's proofread. You should have the business card the tutor signed.

Please let me know if you have any other questions or concerns.

### CODE REVIEW

**Comment by anmolsingh95** [comment]
Hey Manj, just so to save your time, izbicki is going to ask you to combine your commits into a single one. 
http://technoesis.net/git-multiple-commits-in-one-patch/
follow the above tutorial to do that, and submit a new pull request.

**Comment by anmolsingh95** [comment]
Instead of decreasing the number of commits, you just increased them. What I meant was that your pull request should be just one commit.

**Comment by ManjunathChet** [comment]
I am having trouble with git rebase. Everytime I rebase and push, the commits increase. Is there a erase my last commits and start over?

**Comment by ManjunathChet** [comment]
Sorry for the numerous notifications/emails. Figured out how to deal with the commits.

**Pull request closed without merging**
