### PR TITLE
enrolling in cs100

### PR DESCRIPTION
**Pull request by mxu008**
student information added

### CODE REVIEW

**Comment by mikeizbicki** [comment]
I recently (like 10 minutes ago) updated the instruction on what to include in this file.  Please review that and resubmit.  Sorry for the inconvenience.

**Comment by mxu008** [comment]
Hi mike,
I just reclone the repo, but I only can find the instructors folder in the people folder. I can not see the students folder.

**Comment by mikeizbicki** [comment]
This is where the folder is located: https://github.com/mikeizbicki/ucr-cs100/tree/cs100-2014fall/people/students

**Comment by mxu008** [comment]
Thank you!

**Pull request closed without merging**
