### PR TITLE
Combined all of my commits.

### PR DESCRIPTION
**Pull request by jesuscreyes**

### CODE REVIEW

**Comment by jesuscreyes** [comment]
I ran into errors trying to merge the commits made by @mikeizbicki and @hgarc014. I don't believe I have permissions to mess with those, so not sure how to deal with that.

**Comment by mikeizbicki** [comment]
I'm not sure what you're trying to do.  You'll have to be quite a bit more detailed.  The summary stats say that you're adding 395 lines and removing 12.  That seems like way to big of a change for a couple small corrections.

**Comment by jesuscreyes** [comment]
I believe a majority of the line changes came from a commit that you made. If you look at the changes, a lot of them come from the `lecture12` file, which I think came from commits that you made.

And there were other changes that were made by you and Henry, that I just tried to combine into one.

I see that by trying to merge them, I merged the commits that I made with your commit. My commit only include the changes to the `README.md` file for the piping assignment.

Sorry for the mess and the trouble. I'm not sure what I can do from here. Do you have a suggestion for me?

**Comment by mikeizbicki** [comment]
> I believe a majority of the line changes came from a commit that you made. If you look at the changes, a lot of them come from the lecture12 file, which I think came from commits that you made.

The lecture12 file already exists in my repository.  Your commit is trying to add a lecture12 file to my repository redoing all of the changes I already made.  So it doesn't even make sense for me to merge your commit.

There's too many changes like this for me to even figure out what you're trying to do.  I'm pretty sure you explained to me what you were trying to do before, but I forget.  Can you explain the purpose of this pull request again?

**Comment by jesuscreyes** [comment]
The purpose was to merge commits that I made into one so that you could accept those changes into your repo.

It all started with me trying to make changes to the `README.md` file for `hw3`, which included removing the `&` character in the sample command and fixing a grammatical error.

I tried doing a pull request, but you said I needed to merge it into one commit before you could accept it. So I tried using `git rebase -i` to combine my commits.

While I was trying to figure out how to use `git rebase`, commits from you and Henry appeared. So I tried to combine my commits with the both of your commits. This was the result.

**Comment by mikeizbicki** [comment]
Thanks.  What I was looking for was this:

> It all started with me trying to make changes to the README.md file for hw3, which included removing the & character in the sample command and fixing a grammatical error.

I understood you were having problems with git, you just never gave me the context of what you were trying to accomplish.  In the future, make sure to provide a one sentence summary of "what are the benefits of merging your pull request" (that's what I meant by purpose).  The best place to do this is in the pull request title.  Saying just "combine all my commits" doesn't give me any context about why I should care.

---

As for actually fixing the problem, there are at least two mistakes:
1. You have submitted two commits.  The second commit has a whole bunch of commits by other people, AND your commit that's actually important.  You should never combine the commit that you're trying to show someone with other commits, it should always stand alone.
2. Somewhere you made a mistake while rebasing.  It's not obvious to me what the mistake actually was, but I think you might have misunderstood the motivation behind the rebase.  The ONLY purpose of the rebase is to make your repository look exactly like my repository.  That doesn't mean the CONTENT is the same, it means the GIT HISTORY is the same.  I can't imagine this would ever require you to squash commits that you pull from my repo, which it seems like you've done.

**Comment by jesuscreyes** [comment]
Oh ok. I think I misunderstood you and thought that I had to combine my commits with yours. Thanks for the clarification.

I really want to just go back to an older commit before this started, and start fresh. Is that possible?

The reason I ask is because I still want to be able to have  the option to report bugs and add improvements to the course, but this commit problem I created seems to be like a huge wall that keeps me from doing that.

**Comment by hgarc014** [comment]
yes, you can revert to a previous commit. checkout out the commit that you want (before you got a mess). These are some steps you could do in order to get a "fresh" like feeling.
1. revert to a previous commit 
2. force this to your main branch
3. update your forked repository with mike's repository (i use upstream and merge)
4. make necessary changes
5. force this to be your main github repository (in other words something like force push, what a great Jedi reference), you would have to update your github repository, because you would be behind/ahead commits.
6. issue pull request. (before doing this step, make sure your repository on github says something like "you are 1 commit ahead of mikeizbick's project"

I tend to force push after doing step 2 to make sure that I am up to date, but theoretically you should be able to fix everything locally and then force push.

**Comment by jesuscreyes** [comment]
Thanks so much Henry! I'll try to follow the steps you've provided.

**Pull request closed without merging**
