### PR TITLE
Added the pdf file for pointer cheatsheet

### PR DESCRIPTION
**Pull request by ahsu013**

### CODE REVIEW

**Comment by mikeizbicki** [comment]
I'm frustrated that you didn't take any of my suggestions from before.

**Comment by ahsu013** [comment]
I took the suggestions I was able to understand clearly and when I tried to do a follow up, you did not respond. I did what I thought was best and sorry if that frustrated you.

**Comment by mikeizbicki** [comment]
I didn't see any questions you had.  I'd be happy to still answer them.

**Comment by ahsu013** [comment]
I made a rough dough of the cheatsheet and ask if I should continue working under that format or should have fix the old formatting.

**Pull request closed without merging**
