### PR TITLE
strace tutorial revision

### PR DESCRIPTION
**Pull request by cyang032**
Made most of the changes from the comments and added explanations that should answer all the questions from the last pull request. We decided not to incorporate the cp lab.

### CODE REVIEW

**Comment by mikeizbicki** [comment]
Who was your partner?

**Comment by mikeizbicki** [comment]
I need to know to assign the grades.

**Comment by cyang032** [comment]
valeriechiou

**Comment by mikeizbicki** [comment]
100/100 for both of you.

**Pull request merged**
