### PR TITLE
Fixes calcgrade first-run bug

### PR DESCRIPTION
**Pull request by anmolsingh95**
It removes the repetition of git pull that existed in my last pull request.

### CODE REVIEW

**Comment by anmolsingh95** [comment]
but still its your repo so Ill just go with your style.

**Comment by mikeizbicki** [comment]
I see what you're saying.  But the code below doesn't always run.  What if the `$branch` variable is empty because it wasn't passed in as an argument?

The way I have it, `git pull` can in some cases be run twice, which is inefficient.  There's probably a way to rewrite it similar to what you did that guarantees it will be run at most once but will still work when `$branch` is empty.

**Comment by anmolsingh95** [comment]
Since the programmer is actually passing the branch variable, why do we have to check if its empty?

**Comment by anmolsingh95** [comment]
And even before I changed anything. $BRANCH was being used in the script before checking whether its empty or not on line 204 in the config.sh file.

**Comment by anmolsingh95** [comment]
Also, can you please specify what should be done in case $BRANCH is empty. That way it will be easier for me to organize things in an efficient way.

**Comment by mikeizbicki** [comment]
`$branch` is not used before line 204; I don't know what you're talking about?

If 3 arguments are passed into `downloadRepo`, then the repo put itself into whatever branch is passed in as arg 3.  If only 2 args are passed in (i.e. a branch is not specified), then we stay in the default branch on clone (usually `master`, but for this repo it is `cs100-2014fall`) or whatever the previous branch was on pull.

Since the comments weren't clear to you, you should also clarify them.

**Comment by anmolsingh95** [comment]
Thank you, I will add this to the comments.
`$Branch` is used on line 204 and its not been checked before.

**Pull request closed without merging**
