### PR TITLE
revised HW4 submission

### PR DESCRIPTION
**Pull request by ogonz007**
We went through and edited our HW4 to address the issues you brought up concerning the flow of the assignment, and formatting issues.

### CODE REVIEW

**Comment by ogonz007** [comment]
We have updated the README and added a Makefile and final code used for the simulation.

**Comment by mikeizbicki** [comment]
One last thing: you need to squash all your git commits into a single commit before I can merge.

**Comment by ogonz007** [comment]
Do we submit another pull request now that we've squashed the commits?

**Comment by mikeizbicki** [comment]
Yes.

**Pull request closed without merging**
