### PR TITLE
Commit after making changes

### PR DESCRIPTION
**Pull request by skama004**
We made the changes to the program in light of your comments and after rereading the guidelines. My partners @hannesphillips @divyanshch

### CODE REVIEW

**Comment by skama004** [comment]
Please let us know if there's anything we should make better.

**Comment by mikeizbicki** [comment]
You still haven't fixed a number of the mistakes I pointed out, so I can't give you above a 50/100.

Also, your commit 31f3c71 includes file modifications not related to your hw4 submission.  I can't merge until you fix this.  And I'm not going to enter your grade until then.

**Comment by skama004** [comment]
Can we make any changes and resubmit it to get our grade up?

**Comment by mikeizbicki** [comment]
If you showed me something AMAZING in office hours tomorrow I'd give you
more points.  But since your resubmission ignored a lot of the comments I
left the first time around I probably won't be super generous.

**Pull request closed without merging**
