### PR TITLE
Updated README.md for hw2

### PR DESCRIPTION
**Pull request by jesuscreyes**
Hi @mikeizbicki.

Sorry if this pull request is still unacceptable, but if it it, I was wondering if you could help me as I'm still trying to do a successful pull request.

So the two merge commits (`739498b` and `01867eb`) signify that I tried to update my repo to be like yours before I made the pull request.
Commit `9972eba` contains my changes to the `README.md` for `hw2`.

When I try to merge all 3 of my commits into one, I get this error:

`error: Commit 739498b is a merge but no -m option was given.`
`fatal: cherry-pick failed`
`Could not apply 739498b`

First question: Do you know how I can fix this error? Or what's causing it? I tried googling the error, but didn't find anything helpful.

Second question: Is it bad/unacceptable that I have other people's old commits on my repo when I try to do a pull request?

### CODE REVIEW

**Comment by mikeizbicki** [comment]
1. I'm not sure what that error means without a lot more context.  Henry has a pretty good description of the steps to follow to submit a pull request in #507.  If you can't get it working, though, then during office hours tomorrow I'll make helping you fix this a priority.  I know you've been working on it for a while and are probably very frustrated.
2. You _should_ have other people's old commits in your repo, since I have them in my repo as well.

**Comment by jesuscreyes** [comment]
Yeah, I've been trying to implement his steps, but have yet to go through all of them successfully.

I'll continue trying to follow his steps again tonight, and I figure out what the problem was, I'll let you know. Thanks so much Mike!

**Comment by ChemicalWonders** [comment]
I think I might be able to fix yours. You might have added their commits  again, so use git log to see if you have added their commits again.

If you have, remove the other commits by just jumping back to the last known good commit, and you can just git reset <commit> --hard, however, I don't think you should do that unless you know that you had rewritten the old commits again into the history.

I can see if I can help fix your problem if you would lie to meet up?

**Comment by jesuscreyes** [comment]
Thanks @ChemicalWonders, but I actually just figured it out in office hours with @mikeizbicki. You're right! I needed to use git reset --hard. 

Thanks again for offering your help!

**Pull request closed without merging**
