### PR TITLE
third submission

### PR DESCRIPTION
**Pull request by hzhu007**

### CODE REVIEW

**Comment by hzhu007** [comment]
My teammate @renee7547 and I still have two final exams and don't have time to rework. This would be the final version.

**Comment by mikeizbicki** [comment]
The technical information is good, but the writing could use a bit more polish.  85/100

**Comment by Renee7547** [comment]
Hi Mike, could you please tell us the grade we got? Thank you.

**Comment by Renee7547** [comment]
Oh, never mind, I got it.

**Pull request merged**
