### PR TITLE
github name change

### PR DESCRIPTION
**Pull request by plusEight**
Updated personal information on /students/cfan002

File name in which this data is stored is still cfan002. Please let me know if the name of the file itself also needs to be changed.

### CODE REVIEW

**Comment by mikeizbicki** [comment]
You fixed the first part of my previous comments, but you still need to squash the commits into logical chunks.  As is, there's too much going on for me to judge if I should merge or not.

**Comment by mikeizbicki** [comment]
Name of the file should be your csaccount, not github account.  So it shouldn't change.

**Comment by plusEight** [comment]
I am having difficulty with squashing with the git rebase command as shown on the textbook. 

when I use     git rebase -i HEAD~x (in this case i use 10, because that is the number of commits from the latest branch downward that I want to squash) and it shows me over a hundred commits by other students numbering from 1 to 100+

my most recent commit is toward the bottom but some of my recent commits are at the top which makes me question whether or not this list is in chronological order.

Furthermore after closing the text editor that pops up after executing the above command, there are many errors that read something similar to
error: could not apply 91deb70...

**Comment by mikeizbicki** [comment]
It sounds like maybe those commits have been incorporated into my repo, but not into your fork.  You need to update your fork to match my repo before you can squash the commits.  At the very beginning of the writeup is a step using the `git reset` and `git pull` commands that adjusts your repo to be in the same state as mine.  Did you run those commands?

**Comment by Anthony1234567** [comment]
I also had this problem the first time I made a large pull request and had to squash the commits. I solved my problems using some pretty inconventional methods

**Comment by plusEight** [comment]
I have deleted my local repository on my computer and cloned a new one. Then I have ran the git reset and git pull commands to which the terminal said that my branch is up to date. When I run

git rebase -i HEAD~10

it brings up the same large list of commits made by all the other students with myl own commits at both the top and bottom of the list.

If I try tinkering with pick and squash it still gives me a large number of errors when rebasing past a certain number of commits.

**Comment by Anthony1234567** [comment]
I made a folder and cloned Mike's version to that folder
Manually move files where changes were made on to Mike's folder 
Committed those changes in the terminal
Force push to my own github account
Request pull from Mike

**Comment by plusEight** [comment]
I am not sure if I follow. If I clone Mike's folder and make changes there, won't it prevent me from pushing it online because I am not the owner of the repository that I am pushing to?

**Comment by mikeizbicki** [comment]
@plusEight 

> I have deleted my local repository on my computer and cloned a new one.  Then I have ran the git reset and git pull commands to which the terminal said that my branch is up to date.

You didn't provide the actual commands (so I can't know for sure), but it sounds like you ran `git pull origin`.  That will update your local repository with your repo on github.  You need to use the `git remote` command so that you can pull the updates from my repo.

**Pull request closed without merging**
