### PR TITLE
Hw5 - Syscalls

### PR DESCRIPTION
**Pull request by DanTheTingler**
Made changes needed for 95 points - thanks Mike!

### CODE REVIEW

**Comment by mikeizbicki** [comment]
You still have a number of inline code snippets surrounded by things other than backticks.

**Comment by katherinegallaher** [comment]
Can you give me an example of one? I thought I got everything but I was getting confused at the end..

**Comment by DanTheTingler** [comment]
Do we need to put backticks on the numbers as well?

**Comment by mikeizbicki** [comment]
It's not that you missed backticks, it's that you have backticks _and_ something else.  For example there's a (`|`) in there somewhere, and lots of things that look like "`perror`".

As for numbers, I don't really care either way.

**Pull request closed without merging**
