### PR TITLE
Pull Request with squashed commits

### PR DESCRIPTION
**Pull request by jesuscreyes**
I believe that I squashed the commits now. If it still isn't correct, then pull request should be closed.

### CODE REVIEW

**Comment by jesuscreyes** [comment]
Nevermind. Commit `9b16f1c` was meant to be the "merged commit" but I don't think I did what you wanted me to do.

**Comment by mikeizbicki** [comment]
It should show up as just a single commit number when you get it right.

**Comment by jesuscreyes** [comment]
And you want me to merge all of these commits that are listed correct? Including your commits and Henry's commit?

**Comment by mikeizbicki** [comment]
exactly

**Pull request closed without merging**
