### PR TITLE
changed commit message so that grade pulling vunerability is addressed

### PR DESCRIPTION
**Pull request by ChemicalWonders**
included $1 at the end of the line. the commit message reads
"graded assignment using automatic scripts for $1"

hopefully this will address the issue.

### CODE REVIEW

**Comment by mikeizbicki** [comment]
I'm not 100% sure that the commit messages get signed with the commits, so you'll have to point me to documentation that says so.  Also, you'll need to modify the part that verifies the signature to also verify that the username is in the commit message.

**Comment by 2c2c** [comment]
I figured just checking all of the commits in everyone's grades branch for unique shas would be a good approach. It's more work than this, but would ensure there's no more holes possible (besides our NSA overlords).

**Comment by mikeizbicki** [comment]
@2c2c That wouldn't tell you who tried to cheat, only that someone cheated.  Also, I that could very well be vulnerable to a collision attack of some sort.

**Comment by 2c2c** [comment]
Alright, alright. You could always just append the name to the grade file if there's still uncertainty about it being in the commit message.

**Pull request closed without merging**
