### PR TITLE
Updated sample command for Hw#2

### PR DESCRIPTION
**Pull request by jesuscreyes**

### CODE REVIEW

**Comment by mikeizbicki** [comment]
You need to change this to be a single commit before I merge it.

**Comment by jesuscreyes** [comment]
Sorry, I think while trying to figure out how to merge the commits, I ended up adding more commits to it.

Am I supposed to use `git rebase -i` to squash the commits?

**Comment by jesuscreyes** [comment]
Sorry, I think I might have really made a mess of it trying to figure out how to combine all of my commits.

Could you possibly give me directions or a reference to what I need to do?

**Comment by mikeizbicki** [comment]
`git rebase` is the command that you'll want to look into, but it can be pretty tricky to use.  Check out this link:
http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
and scroll down to the section on squashing commits.  That should get you through it.

**Pull request closed without merging**
