### PR TITLE
enrolling in CS100

### PR DESCRIPTION
**Pull request by KenleyArai**

### CODE REVIEW

**Comment by mikeizbicki** [comment]
Why didn't you complete this in lab today?

**Comment by tkimva** [comment]
He wasn't in my class roster today. 
Kenley,
Please come to my office hour tomorrow 3:40-5:00 WCH110

**Comment by KenleyArai** [comment]
I had food poisoning from the night before, and wasn't able to make it to the lab. I completely apologize for the inconvience. 

I did do the work for the lab prior to the lab, but I understand the lab is mandatory and not making it to the lab means no points. 

EDIT: 

I just re-read the the comments. I have CS 11 in the same room from 3:40 - 5:00 tomorrow.
Is there another time we can meet?

**Comment by tkimva** [comment]
How about 10 min during 12:40-2pm, Let me know

**Comment by KenleyArai** [comment]
I will be there.

**Comment by tkimva** [comment]
Meet at Byte at 12:40 quick.

**Comment by tkimva** [comment]
After deep discussion with Prof. Izbikci, we have to decide give you no credit for the lab-01. So we don't need to meet tomorrow. See you on next Monday.

**Comment by tkimva** [comment]
Great job though.

**Pull request merged**
