### PR TITLE
all the textbook markdown files fixed,

### PR DESCRIPTION
**Pull request by ikim025**
Hello Mike, I fixed the all the markdown files that was in the /textbook

Every sentence now has its own line.
I fixed table of contents (guideline said DO NOT put table of contents)
fixed I/me to we/us
fixed past tense to present tense in most cases ( some were describing the history such as 'has worked' and 'is called')
shorten the code blocks as it is most easy to read
checked for the first sentence to be the description of the lesson
corrected some spelling and grammar error.

Thank you,

### CODE REVIEW

**Comment by mikeizbicki** [comment]
I'm sorry that I can't accept this patch as-is.  It appears you made your revisions to an older version of the `ucr-cs100` repo.  A lot of the files have been modified since your version.  If I accepted your patch, it would undo everyone else's modifications.

Also, I'm not sure what those first three commits are supposed to be doing.  You'll have to resubmit.

**Comment by ikim025** [comment]
if I would resubmit, do I clone the current winter2015 and fix the textbook files? or what do i have to do in order to fix the current one?

**Comment by ikim025** [comment]
in addition, could I possibly download the files fixed recently perhaps from last 2 months and fix all those files in the textbook? 
Or do I have to re download the current repository if cs100 and start from scratch?

**Comment by ikim025** [comment]
in addition, could I possibly download the files fixed recently and compare the differences on the changed files I have?  
Or do I have to re download the current repository of cs100 and start from scratch?

**Comment by mikeizbicki** [comment]
I need it to be that I just click on the button "merge pull request" and
everything will work fine.  There's many possible ways to get it to that
point, and I'm sorry but I don't have the time to go step-by-step on how to
do it.  The file `textbook/tools/git/managingForkedRepos/` should help you
out.

**Comment by ikim025** [comment]
okay  I will get right on that. so simply fixing what is on our current repository would work fine right? the one currently on ucr-cs100 of your repos

**Comment by mikeizbicki** [comment]
yes.  I will be adding things to a new branch 2015spring in a bit, but you
don't need to worry about that

**Pull request closed without merging**
