### PR TITLE
enrolling in cs100

### PR DESCRIPTION
**Pull request by mxu008**
enrolling in cs100

### CODE REVIEW

**Comment by mxu008** [comment]
When we update the forked repository on the github servers, I think we should run the command "git push origin ucr-cs100" instead of "git push origin master"

**Comment by tkimva** [comment]
`git push  <REMOTENAME> <LOCALBRANCHNAME>:<REMOTEBRANCHNAME>`
Usually run `git push origin master` to push local change to your github repository, but we don't have `master` branch and use `cs100-2014fall`

**Comment by mikeizbicki** [comment]
@mxu008 That's a bug in the instructions you've found.  Can you edit the page in your forked branch (make sure you're in the `cs100-2014fall` repo) and send a pull request?  I'll give you extra credit for the change.

**Comment by mxu008** [comment]
@mikeizbicki I think someone has edited the page. Will I get extra credit for the change?

**Comment by mikeizbicki** [comment]
The page hasn't been updated, so I don't know what you're talking about.

**Pull request merged**
